# pytorch-lightning==2.2.4
seed_everything: 23052024
data:
  class_path: datamodules.NerDataModule
  init_args:
    dataset: data/A/traindata_3.json
    batch_size: 32
    num_workers: 18
    tagset_path: resources/tagsets/ner_tagset.json
    pretrained_model: distilbert-base-multilingual-cased
    data_pkl: A_dmbert.pkl
    use_unk_classes: false
model:
  class_path: models.NERModel
  init_args:
    learning_rate: 4.0e-05
    report_unk_class_pmass: false
    weighted_loss: false
trainer:
  accelerator: auto
  strategy: auto
  devices: 1
  num_nodes: 1
  precision: 32-true
  logger:
    - class_path: lightning.pytorch.loggers.mlflow.MLFlowLogger
      init_args:
        experiment_name: A_dmbert
        run_name: dev
  fast_dev_run: false
  max_epochs: 40
  min_epochs: 1
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  limit_test_batches: 1.0
  limit_predict_batches: 1.0
  overfit_batches: 0.0
  val_check_interval: null
  check_val_every_n_epoch: 1
  num_sanity_val_steps: 1
  log_every_n_steps: 10
  enable_checkpointing: false
  enable_progress_bar: null
  enable_model_summary: null
  accumulate_grad_batches: 1
  gradient_clip_val: null
  gradient_clip_algorithm: null
  deterministic: true
  benchmark: null
  inference_mode: true
  use_distributed_sampler: true
  profiler: null
  detect_anomaly: false
  barebones: false
  plugins: null
  sync_batchnorm: false
  reload_dataloaders_every_n_epochs: 0
ckpt_path: null
